### PR TITLE
Fix location no method error

### LINKED ISSUE #692: Error `undefined method 'selector' for #<Parser::Source::Map::Operator...` with usage of `+=` when no method error would be raised
Really enjoying working with RBS and steep! Thanks very much for all your work on it!

Take for example  the following:

```ruby
x = 1

x = nil if ARGV.size > 0

x += 1
```

Running `steep check` on this crashes.

I think the crash is related to the use of `+=`. Changing to `x = x + 1` instead of `x += 1` then we see the expected `Type '(nil | ::Integer)' does not have method '+'` 

The stack trace is as follows:

```
[Steep 1.3.0] [typecheck:typecheck@6] [background] [#typecheck_source(path=lib/test.rb)] [#type_check_file(lib/test.rb@lib)] [synthesize:(1:1)] [synthesize:(5:1)] [synthesize:(5:1)] [synthesize:(5:6)] Unexpected error: #<NoMethodError: undefined method `selector' for #<Parser::Source::Map::Operator:0x0000000109a9e098 @operator=nil, @expression=#<Parser::Source::Range lib/test.rb 38...39>, @node=s(:int, 1)>

                  node.loc.selector
                          ^^^^^^^^^>
[Steep 1.3.0] [typecheck:typecheck@6] [background] [#typecheck_source(path=lib/test.rb)] [#type_check_file(lib/test.rb@lib)] [synthesize:(1:1)] [synthesize:(5:1)] [synthesize:(5:1)] [synthesize:(5:6)]   /Users/stephen/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/steep-1.3.0/lib/steep/diagnostic/ruby.rb:242:in `initialize'
[Steep 1.3.0] [typecheck:typecheck@6] [background] [#typecheck_source(path=lib/test.rb)] [#type_check_file(lib/test.rb@lib)] [synthesize:(1:1)] [synthesize:(5:1)] [synthesize:(5:1)] [synthesize:(5:6)]   /Users/stephen/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/steep-1.3.0/lib/steep/type_construction.rb:3029:in `new'
[Steep 1.3.0] [typecheck:typecheck@6] [background] [#typecheck_source(path=lib/test.rb)] [#type_check_file(lib/test.rb@lib)] [synthesize:(1:1)] [synthesize:(5:1)] [synthesize:(5:1)] [synthesize:(5:6)]   /Users/stephen/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/steep-1.3.0/lib/steep/type_construction.rb:3029:in `type_send_interface'
[Steep 1.3.0] [typecheck:typecheck@6] [background] [#typecheck_source(path=lib/test.rb)] [#type_check_file(lib/test.rb@lib)] [synthesize:(1:1)] [synthesize:(5:1)] [synthesize:(5:1)] [synthesize:(5:6)]   /Users/stephen/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/steep-1.3.0/lib/steep/type_construction.rb:3089:in `type_send'
[Steep 1.3.0] [typecheck:typecheck@6] [background] [#typecheck_source(path=lib/test.rb)] [#type_check_file(lib/test.rb@lib)] [synthesize:(1:1)] [synthesize:(5:1)] [synthesize:(5:1)] [synthesize:(5:6)]   /Users/stephen/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/steep-1.3.0/lib/steep/type_construction.rb:2478:in `block in synthesize_sendish'
[Steep 1.3.0] [typecheck:typecheck@6] [background] [#typecheck_source(path=lib/test.rb)] [#type_check_file(lib/test.rb@lib)] [synthesize:(1:1)] [synthesize:(5:1)] [synthesize:(5:1)] [synthesize:(5:6)]   <internal:kernel>:148:in `yield_self'
...
```

### PR DESCRIPTION
**Pull request by soutaro**
Closes #692

### CODE REVIEW

File: lib/steep/diagnostic/ruby.rb [hunk 1]
```diff
@@ -286,7 +286,13 @@ class NoMethod < Base
         def initialize(node:, type:, method:)
           loc = case node.type
                 when :send
-                  node.loc.selector
+                  loc = node.loc
+
+                  if loc.respond_to?(:operator)
```
Comment (soutaro) [inline lib/steep/diagnostic/ruby.rb:291]: Using `respond_to?` as the Parser gem recommends.

https://github.com/whitequark/parser/blob/master/lib/parser/source/map.rb#L44-L48
